trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  branch: "$(Build.SourceBranchName)"
  tag: "$(Build.SourceVersion)"
  ImageName: "hauki"
  azureSubscription: HKI-kanslia-standalone
  appName: hauki
  containerRegistry: registry.hub.docker.com
  tag_postfix: "apm"

steps:
  - script: |
      echo 'Running in workspace $(Pipeline.Workspace)'
      echo 'Build.SourceBranchName: $(branch)'
      echo 'Build.SourceVersion: $(tag)'
      echo 'Build.SourcesDirectory: $(Build.SourcesDirectory)'
      echo 'Build.ArtifactStagingDirectory: $(build.artifactstagingdirectory)'
      echo 'Tags: $(tag_postfix)'
  - task: NodeTool@0
    inputs:
      versionSpec: "16.15.1"
    displayName: "Install Node.js"
  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      command: "login"

  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      repository: "9876543232/mind-platform"
      command: "build"
      Dockerfile: "**/Dockerfile"
      tags: |
        $(tag)_latest
    displayName: "Docker image build"

  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      repository: "9876543232/mind-platform"
      command: "push"
    displayName: "Docker image push"
  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      command: "logout"
