trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  imageTag: "latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.15.1"
    displayName: "Install Node.js"
  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      command: "login"

  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        Write-Host "##vso[task.setvariable variable=imageTag]$(Build.BuildNumber)"
    displayName: "Set image tag variable"

  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      repository: "9876543232/mind-platform:$(imageTag)"
      command: "build"
      Dockerfile: "**/Dockerfile"
    displayName: "Docker image build"

  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      repository: "9876543232/mind-platform"
      command: "push"
    displayName: "Docker image push"
  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      command: "logout"
