trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.15.1"
    displayName: "Install Node.js"
  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      command: "login"

  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      repository: "9876543232/mind-platform:latest"
      command: "build"
      Dockerfile: "**/Dockerfile"
    displayName: "Docker image build"

  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      repository: "9876543232/mind-platform"
      command: "push"
    displayName: "Docker image push"
  - task: Docker@2
    inputs:
      containerRegistry: "docker hub services"
      command: "logout"
